# Generated by Django 3.1.3 on 2020-11-19 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=22, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('ponto_referencia', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segunda', models.TimeField(default=django.utils.timezone.now)),
                ('segunda_fecha', models.TimeField(default=django.utils.timezone.now)),
                ('terca', models.TimeField(default=django.utils.timezone.now)),
                ('terca_fecha', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor_percentual', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('avaliacao', models.IntegerField(default=0, verbose_name='numero_documentos_criar_mes_direito')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venda_comida.endereco')),
                ('horarios', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='venda_comida.horarios')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField(default=None, verbose_name='quantidade')),
                ('preco', models.FloatField(blank=True, default=None, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='foto_produto/')),
                ('promocao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venda_comida.promocao')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoCarrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.IntegerField(default=0, verbose_name='numero_documentos_criar_mes_direito')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venda_comida.cliente')),
                ('produtos', models.ManyToManyField(related_name='produtos_no_historico', to='venda_comida.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venda_comida.endereco'),
        ),
        migrations.CreateModel(
            name='ClasseDeProdutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('produtos', models.ManyToManyField(related_name='produtos_da_classe', to='venda_comida.Produto')),
                ('promocao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venda_comida.promocao')),
                ('restaurante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venda_comida.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venda_comida.cliente')),
                ('produtos', models.ManyToManyField(related_name='produtos_no_carrinho', to='venda_comida.Produto')),
            ],
        ),
    ]
