# Generated by Django 3.1.3 on 2020-11-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda_comida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=22, unique=True),
            preserve_default=False,
        ),
    ]
