# Generated by Django 3.1.3 on 2020-11-19 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda_comida', '0003_auto_20201119_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classedeprodutos',
            name='promocao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venda_comida.promocao'),
        ),
    ]
